# Generated by Django 4.2.30 on 2026-04-18 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vault", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="record",
            name="document",
            field=models.FileField(blank=True, null=True, upload_to="documents/"),
        ),
    ]
