# Generated by Django 4.2.30 on 2026-04-20 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vault", "0002_record_document"),
    ]

    operations = [
        migrations.AddField(
            model_name="record",
            name="reminder_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
